### ISSUE TITLE
Feature request: Sync from DayBefore

### ISSUE THREAD

**Issue by heiko-huetter** [Matthewspear/OFHabitRPG#1]
I think it would be great if you'd be able to not only sync the current day, but also the day before, depending on a configurable variable.

I use your script within alfred (http://www.alfredapp.com/) as a workflow and would love to just put "omni2habit today" or "omni2habit yesterday" in the searchbar to quickly achieve just that. 

By the way, nice work! Helps me a lot.

**Comment by matthewspear** [comment]
Yeah that's a neat idea - how do you think I could best work?
Either:
- option in script for users to choose between today, yesterday
  - prompt pop up asking which day
  - or so kind of smart tracking so it knows what you have / havn't logged to HabitRPG

The last one could take slightly longer to do!

**Comment by heiko-huetter** [comment]
I think the second one would be the best possible option, if you're sure that's possible. I don't know whether OF gives you any functionality for this which would prevent you from messing around with the whole synchronization complexity.

In case you go for option 1: I'd suggest the following:

Have a variable at the top:
syncday = ...

can be of value 
undefined (default and causes the prompt you suggested)
yesterday
today

that way it would be possible to use the script as i described above within alfred ;-)

**Comment by matthewspear** [comment]
Done it - made a branch in the project called yesterday-today: https://github.com/Matthewspear/OmniRPG/tree/yesterday-today

Now I just did both:
- Script for both Today and Yesterday (easier for you using alfred?)
  - Main script with dialog and option at top to turn the dialog off

Give it a go and tell me how you get on and any other feedback :D

**Comment by heiko-huetter** [comment]
works like a charm! Minor glitch: In the yesterday script it shouldn't state "Tasks completed TODAY" in the popup ;-)

Many thanks

**Comment by matthewspear** [comment]
Yeah I also noticed that after pushing it - all updated now :+1:
