### ISSUE TITLE
Add more instructions on creating API credentials

### ISSUE THREAD

**Issue by lukaskollmer** [Matthewspear/OFHabitRPG#3]
The link you provided in the read me forwards to the root of the domain, meaning that the api credentials cannot be created by the user. Please provide further information on how to create/retrieve the credentials required to use your scripts 

Thank you!

**Comment by matthewspear** [comment]
Sure first I'll get you sort, then I'll update the documentation!

Does this link work: https://habitica.com/#/options/settings/api ?

Otherwise within HabitRPG (now called Habitica) you will have to click on the cog in the top right corner and select API.

Did either of those help?

Matt

**Comment by matthewspear** [comment]
Hey @lukaskollmer , I've just pushed a few commits fixing the setup and logging scripts. If you've installed OmniRPG in the past, delete any related habits with the new versions as there are some changes to the API that don't allow for backward compatibility.

If you are still having problems let me know by create another issue!
