### ISSUE TITLE
Doesn’t work?

### ISSUE THREAD

**Issue by vicyork** [Matthewspear/OFHabitRPG#4]
Hi, installed, run scripts, however, nothing changes on my habitica site. Does this not work yet?

**Comment by matthewspear** [comment]
Right two things to check first, have you:
- Run the Setup Script
- Added Your API Keys to the main OmniRPG.scpt

Mine is working fine - I firing of the script, go to the site and hit refresh and the pre-made habits are triggered, experience can be seen in the top right and the graph for the habit increases. 

Out of interest what version of OmniFocus are you using?
Standard / Pro?
Site Version / Mac App Store Version?

Tell me how you get on, if this doesn't work we can try something else!

**Comment by matthewspear** [comment]
Hey @vicyork , I've just pushed a few commits fixing the setup and logging scripts. If you've installed OmniRPG in the past, delete any related habits with the new versions as there are some changes to the API that don't allow for backward compatibility.

If you are still having problems let me know by create another issue!
