### ISSUE TITLE
basics

### ISSUE THREAD

**Issue by tspowell** [Matthewspear/OFHabitRPG#5]
Sorry, don't have a ton of script experience so this is a bit bewildering to me. A few questions:
1. Is there a way to automatically set the OmniRPG script to run automatically every day? 
2. do I have to set up a corresponding habit to the tasks in omnifocus? 

sorry, how to actually put these two things together is eluding me.

**Comment by matthewspear** [comment]
1. Yes, I use a free application called [Task Till Dawn](http://www.oliver-matuschin.de/en/projects/task-till-dawn), which I schedule to run 23:55 everyday to catch any completed tasks and get points from them.
2. Yes, but you do that by running the Setup.scpt first and putting in your [API Keys from the Habitica  website](https://habitrpg.com/#/options/settings/api), which will create 3 habits called low, medium and high.

Once setup all you need to do is mark tasks in OmniFocus with either a context @low, @medium, @high or write LOW, MEDIUM or HIGH in the note section of a task for it to be counted.

Tell me how you get on and fire me back any questions you have!!

**Comment by tspowell** [comment]
I ran the setup.scpt and input my keys when prompted, but nothing seems to be pushing to my habitica?

**Comment by matthewspear** [comment]
I've just re-ran the script for myself and worked for me - check that the script is running in the same folder as the low.json, medium.json and high.json files.

**Comment by matthewspear** [comment]
Hey @tspowell , I've just pushed a few commits fixing the setup and logging scripts. If you've installed OmniRPG in the past, delete any related habits with the new versions as there are some changes to the API that don't allow for backward compatibility.

If you are still having problems let me know by create another issue!
