### ISSUE TITLE
Habit Validation Fails

### ISSUE THREAD

**Issue by emsariel** [Matthewspear/OFHabitRPG#6]
I've downloaded the package, pulled up the Habitica API page, and run Setup.scpt.  I put in my id and key, the script crunches along for a few moments, and:

`"{\"err\":\"habit validation failed\"}"`

What's gone wrong?  How can I set up the habits manually?

**Comment by emsariel** [comment]
Hm.  A bit more detail - I tried reconstructing the commands from the script in Terminal.  I made this:

`curl -X POST --compressed -H 'Content-Type:application/json' -H 'x-api-user:myUserIDHidden' -H 'x-api-key:myAPIKeyHidden' -d @/Applications/OmniRPG-master/::low.json https://habitrpg.com:443/api/v2/user/tasks`

and I get the error: 

```
Warning: Couldn't read data from file 
Warning: "/Applications/OmniRPG-master/::low.json", this makes an empty POST.
{"userId":"myUserIDHidden","text":"text","type":"habit","notes":"","tags":{},"value":0,"priority":1,"attribute":"str","challenge":{},"reminders":[],"_id":"That","createdAt":"2016-07-19T03:09:50.357Z","updatedAt":"2016-07-19T03:09:50.357Z","history":[],"down":true,"up":true,"id":"myAPIKeyHidden","dateCreated":"2016-07-19T03:09:50.357Z"}
```

**Comment by matthewspear** [comment]
I have a feeling HabitRPG has gone through some changes as it turned into Habitica. The script was written on v2 of the API which has recently been deprecated for v3. I have stopped using this script but will do my best to keep it up to date. PR are always welcome!!

**Comment by matthewspear** [comment]
Hey @emsariel, I've just pushed a few commits fixing the setup and logging scripts. If you've installed OmniRPG in the past, delete any related habits with the new versions as there are some changes to the API that don't allow for backward compatibility.

Let me know how it works out for you, I would love your feedback and create another issue if you come across any problems!

**Comment by emsariel** [comment]
I figured that it was API changes.  I'll try the new version and 

I'm excited by this, and if I can come to understand how it's working, I'll see whether I can contribute in the future.  Thank you for looking into it -- and so quickly!

**Comment by matthewspear** [comment]
No worries, just let me know if you need any more help!
