### ISSUE TITLE
Where might feature requests go?

### ISSUE THREAD

**Issue by emsariel** [Matthewspear/OFHabitRPG#7]
Hello -- As I'm starting to use this, I'm thinking of a few features, for the latest version of Habitica, that I'd find useful.  The existing 'roadmap' as well as this list would also serve well for things I'd like to look into adding myself as I come up to speed on this.  I'm still young to GitHub; where is a good place to keep these sorts of lists, for this project?

**Comment by matthewspear** [comment]
I would suggest making an issue with the suggested feature, that gives us a place to easily discuss it, others to see / join in and then decisions to be made (what, how and who). Issues can also be tagged to clearly see what they are about, so unless I can add my own "feature" label, "enhancement" will do for the moment.

I've copied the roadmap from the wiki, plan on moving it away from the README.md and reference where people can find it if they are interested and welcome people to suggest requests via submitting issues.

One other thought is that maybe it should be renamed to "Omnitica" to match the change from HabitRPG > Habitica.

Happy to show you the little I know about GitHub!

**Comment by emsariel** [comment]
That makes sense to me!  I'll file a few issues shortly.  I'm mostly looking over the v3 API and noting some things that could be modeled more, like recognizing task attributes (strength, intelligence, etc), or even setting completed tasks as tasks and recurring tasks as dailies or habits rather than all going through a habit.

I'm not sure all of those are good ideas, so being able to discuss them is great!
